# -*- coding: utf-8 -*-
"""Guess The Number *Completed*

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HUOaJLbctxvCUegb4M8Bak9XXWlKqZii
"""

# This is a guessing game

import sys, random

guessesTaken = 0

input("\nPress Enter to start.")

print("Hello! What is your name?")
myName = input()

number = random.randint(1, 50)
print("Welcome " + myName + ", I am thinking of a number between 1 and 50.")

for guessesTaken in range(6):
  print("Take a guess.")
  guess = input()
  guess = int(guess)

  if guess < number:
    print("Your guess is too low")

  if guess > number:
    print("Your guess is too high")

  if guess == number:
    break

if guess == number: 
  guessesTaken = str(guessesTaken + 1)
  print("Congrats " + myName + ", you guessed my number in " + guessesTaken + " guesses!")

if guess != number:
  number = str(number)
  print("Nope. The number I was thinking of was " + number + ".")

else: 
  input("Press Enter to Exit")